---
# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported system or architecture.
- name: Assert platform is supported
  tags: packerio
  assert:
    that:
      - ansible_os_family in ['Archlinux', 'Debian', 'RedHat', 'Suse']
      - ansible_architecture in ['x86_64']


#   Packer download link alters based on system and architecture
- include_vars: "{{ ansible_system }}.yml"
  tags: packerio

#   Ensure unarchive modules' dependencies
- include_vars: "{{ ansible_os_family }}.yml"
  tags: packerio

- name: Install unarchive module dependencies
  tags: packerio
  with_items: packerio_package_list
  action: "{{ ansible_pkg_mgr }} state=present name={{ item }}"


#   Download packer to the local source directory
- name: Ensure download directory (local)
  tags: packerio
  local_action: file
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ ansible_data_path }}

- name: Download packer.io distribution (local)
  tags: packerio
  local_action: get_url
    url={{ packerio_mirror }}/{{ packerio_filename }}
    dest={{ ansible_data_path }}/{{ packerio_filename }}
    owner=0
    group=0
    mode=0644
    sha256sum={{ packerio_sha256sum }}


#   Install packer
- name: Ensure installation directory
  tags: packerio
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ packerio_install_dir }}/{{ packerio_version }}

- name: Install packer
  tags: packerio
  unarchive:
    src={{ ansible_data_path }}/{{ packerio_filename }}
    dest={{ packerio_install_dir }}/{{ packerio_version }}

- name: Linking binaries into system PATH
  tags: packerio
  when: packerio_bin_path != packerio_install_dir
  with_fileglob: packerio_install_dir + '/' + packerio_version + '/packer*'
  file:
    state=link
    force=true
    src={{ item }}
    dest="{{ packerio_bin_path }}/{{ item|basename }}"
